### ISSUE TITLE
同步

### ISSUE THREAD

**Issue by azole** [iiijimhsu/nodejs-mfee16#1]
https://github.com/iiijimhsu/nodejs-mfee16/blob/cf6d175e56db37d6bfc3cad16f1a663a92087b46/basic/index.html#L33

可以的話也練習看看同步請求

**Comment by iiijimhsu** [comment]
謝謝老師提醒,有練習操作了。

**Comment by azole** [comment]
#1, #2, #3 都可以關掉啦，做得很好
