### ISSUE TITLE
axios.get 不是應該要去證交所嗎？

### ISSUE THREAD

**Issue by azole** [iiijimhsu/nodejs-mfee16#4]
https://github.com/iiijimhsu/nodejs-mfee16/blob/40da7962dcf37c8ee552f1bd12c2c43381401ce6/crawler/appsql.js#L34

axios.get 是不是應該要去 `https://www.twse.com.tw/zh/api/codeQuery?query=${stockCode}` 這裡查詢呢？

**Comment by iiijimhsu** [comment]
對，老師謝謝，已經更正了。
